In [1]:
#Ejercicio 10

import pandas as pd

import os

import numpy as np

import scipy.io as sio

from scipy import stats

from math import factorial

import seaborn as sns

from scipy.linalg import eigh,eig,eigvals

from scipy.optimize import linprog

import matplotlib.pyplot as plt

from copy import deepcopy

import sys

from scipy.spatial import distance as dist

import copy

import numpy as np

from scipy.optimize import linprog

from basic_utils import nn2na, get_usage_string, get_min_cut

# IMPORT THE DATA:
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])

# DATA MANIPULATION:

Aeq, arc_idxs = nn2na(NN)
beq = np.array([1, 0, 0, 0, 0, -1])
bounds = tuple([(0, None) for arcs in range(0, Aeq.shape[1])])

# Costos  
C=np.array([2, 1, 2, 5, 2, 1, 2])
# Tiempo de cada Arco
C_t=np.array([3, 1, 3, 1, 3, 3, 5])
# Restricción de tiempo
T=8

print('## Optimizer inputs ## \n'
      'Cost vector: %s \n '
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds))

# Lambdas a probar
lamb=np.array([0.001, 0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 1])
L=np.zeros(len(lamb))

for i in range (11):
  C_aux=(C+(C_t*lamb[i]))
 
    # OPTIMIZE:
  res = linprog(C_aux,   A_eq=Aeq, b_eq=beq   , bounds=bounds, method='simplex')

  # L(lamb)=min (_C*X) - lambda*T
  L[i]=res.fun -lamb[i]*T  
 
  # GET THE SOLUTION:
  selarcs = get_selected_arcs(arc_idxs, res.x)
  print(' ')
  print('Lambda=', lamb[i])
  print('~Cost:',C_aux)
  print('The raw solution will be: %s' % res.x)
  print('The arcs that make the shortest path will be (from, to): %s' % selarcs)
  print('The the L value is: %0.2f ' % L[i])
 
print(' ')    
print('The values of L is : ',L)
plt.xlabel('lambda')
plt.ylabel('L(lambda)')
plt.plot(lamb,L)



## Optimizer inputs ## 
Cost vector: [2 1 2 5 2 1 2] 
 A_eq Node-Arc matrix:
[[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]] 
b_eq demand-supply vector: [ 1  0  0  0  0 -1] 
Bounds of each X arc variable: ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



<ipython-input-1-50ac0da9ca3f>:72: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  res = linprog(C_aux,   A_eq=Aeq, b_eq=beq   , bounds=bounds, method='simplex')


NameError: name 'get_selected_arcs' is not defined