In [4]:
#Ejercicio 8

import pandas as pd

import os

import numpy as np

import scipy.io as sio

from scipy import stats

from math import factorial

import seaborn as sns

from scipy.linalg import eigh,eig,eigvals

from scipy.optimize import linprog

import matplotlib.pyplot as plt

from copy import deepcopy

import sys

from scipy.spatial import distance as dist

import copy


import numpy as np

from scipy.optimize import linprog

from basic_utils import nn2na, get_usage_string, get_min_cut



## Estructura de la matriz NN:

##  P1A P1B P2A P2B P3A P3B     S1A S1B  S2A S2B         V1A V1B  V2A V2B  V3A V3B


NN= np.array([

    [     0, 0, 0, 0, 0, 0,         1, 0, 1, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 1, 0, 1,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         1, 0, 1, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 1, 0, 1,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         1, 0, 1, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 1, 0, 1,                  0, 0, 0, 0, 0, 0,   ],
   
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  1, 0, 1, 0, 1, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 1, 0, 1, 0, 1,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  1, 0, 1, 0, 1, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 1, 0, 1, 0, 1,   ],
   
   
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 0, 0, 0, 0, 0,   ],
    [     0, 0, 0, 0, 0, 0,         0, 0, 0, 0,                  0, 0, 0, 0, 0, 0,   ],


])

# DATA MANIPULATION

NA, arc_idxs = nn2na(NN)
m,n=NA.shape

A=np.zeros((m,n))
A[0:6,:]=NA[0:6,:]


Aeq=np.zeros((m,n))
Aeq[6:m,:]=NA[6:m,:]

C = np.array([100,100,  200,200   ,150,150,       150,150,   200,200    ,100,100,
             
              100,150 ,200,     200,150,100,      100,150 ,200,   200,150,100,])


b_A = np.array([20,30,10,40,30,10,  0,0,0,0,  0,0,0,0,0,0])

beq = np.array([0,0,0,0,0,0,  0,0,0,0,  -30,-40,-10,-20,-20,-20])


               
bounds = tuple([(0, None) for arcs in range(0, NA.shape[1])])

print('## Optimizer inputs ## \n'
      'Cost vector: %s \n '
      'A Node-Arc matrix:\n%s \n'
      'b_A offert-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, A, b_A, bounds))




print('## Optimizer inputs ## \n'
      'Cost vector: %s \n '
      'A_eq Node-Arc matrix:\n%s \n'
      'b_eq demand-supply vector: %s \n'
      'Bounds of each X arc variable: %s \n' % (C, Aeq, beq, bounds))



# OPTIMIZE:
res = linprog(C,  A_ub=A, b_ub=b_A,   A_eq=Aeq, b_eq=beq    , bounds=bounds, method='simplex')



max_flow = res.fun * -1
print('## Results ## \n'
      'The maximum flow will be: %0.2f ' % ( max_flow))



# GET THE SOLUTION:

print('The raw solution will be: %s' % res.x)


## Optimizer inputs ## 
Cost vector: [100 100 200 200 150 150 150 150 200 200 100 100 100 150 200 200 150 100
 100 150 200 200 150 100] 
 A Node-Arc matrix:
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0